services:
  postgres:
    image: postgres:16
    container_name: gartenzwerge-postgres
    environment:
      POSTGRES_DB: gartenzwerge_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - gartenzwerge_postgres_data:/var/lib/postgresql/data

volumes:
  gartenzwerge_postgres_data: